language: elixir

matrix:
    include:
        - elixir: 1.7
          otp_release: 21.0
        - elixir: 1.6
          otp_release: 21.0
        - elixir: 1.4
          otp_release: 18.2.1

script:
    - mix test
    - if [[ $TRAVIS_ELIXIR_VERSION = "1.7" ]]; then mix docs; fi
    - if [[ $TRAVIS_ELIXIR_VERSION = "1.7" ]]; then mix format --check-formatted; fi
